version: '3.5' # 3.5 because we currently use it on CentOS 7
services:
  ULBDiscordBot:
    image: bepolytech/ulbdiscordbot:latest # or version like :1.2
    container_name: ULBDiscordBot
    #build:
    #  context: .
    #  image: ulbdiscordbot
    #  dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/usr/src/ulbdiscordbot
    restart: always # or unless-stopped
